### ISSUE TITLE
Q: relation to rails, 5.1?

### ISSUE THREAD

**Issue by jrochkind** [Azdaroth/active_model_attributes#2]
Thanks for providing this! I was just poking about in the AR/AM::Type stuff, trying to figure out a way to do something clever with postgres jsonb, and I noticed that AM did not implement this, and was surprised.  So then I found this!

Do you know what the current status of this is in Rails itself or it's roadmap? Does Rails plan include this functionality eventually?  Apparently it didn't make it into 5.1, it doesn't look like?  Will this gem work in Rails 5.1, do you know, have you tested it yet?  How safe do you think it is to rely on the functionality in this gem long-term?

Thanks for any advice!

**Comment by jrochkind** [comment]
I wrote this before looking at the source -- it's quite simple!  Which makes me feel pretty good about relying on it -- but any idea why they don't just put this in Rails?  Have you tried PR'ing it? 

Curious on any background or context here you may have -- it's surprising this isn't already a part of ActiveModel, no?

**Comment by Azdaroth** [comment]
Hey @jrochkind 

Initially, exactly the same code was the part of the PR I submitted to Rails hoping it would be merged and released with AM 5.1 . The problem was that Rails core team wanted something that would be more "integrated" with the rest of the Rails and unified with ActiveRecord Attributes API. I wanted to give it a try, but AR code is pretty complex and I didn't have much time to unify this concept between AR and AM, so I released this gem.

Haven't tested it with 5.1 yet, but I think it should work, it depends only on the very essential AM API, which won't probably change until Rails 6 at earliest.

**Comment by jrochkind** [comment]
thanks for the context!  Apparently nobody else made any more progress with 'more integrated' before Rails 5.1. What you've got already seems reasonably integrated with what Rails does to me; any idea what shape they imagined that 'more integrated' would take? 

I'm digging into this Type stuff to try to do something that combines some aspects of https://github.com/devmynd/jsonb_accessor and some aspects of this, to support really cool seamless multi-level nested objects in a postgres jsonb column. If that makes any sense. Hard to explain. 

Seems basically do-able with the pretty cool Rails5 attribute/type API... but indeed there are a lot of parts to figure out and pay attention to.

**Comment by jrochkind** [comment]
I don't know if they gave you any more specific feedback on the PR to Rails, but if you still have a URL to it handy I'd be curious to check it out!

**Comment by Azdaroth** [comment]
@jrochkind Here's the PR: https://github.com/rails/rails/pull/26728 . But not idea really if it has progressed anyhow and what are the future plans for it. But hey, at least we have  `active_model_attributes` available ;)

**Comment by jrochkind** [comment]
I ended up writing something related to this functionality, but specifically focused on embedding typed ActiveModels in a serialized json column. Currently experimental, but seems to be working out well, feedback very welcome. https://github.com/jrochkind/json_attribute
