### ISSUE TITLE
ActiveModel::Type::DateTime does not return a DateTime object

### ISSUE THREAD

**Issue by sarah-i-nbr** [Azdaroth/active_model_attributes#7]
Hi! Really nice gem. Found a small tiny issue and I am wondering if this is intentional.

I am trying to use the build in datetime type in my non-ActiveRecord object like so:

`attribute :from_time, :datetime` 

However the object returned is `Time`. 
```
from_time.class
=> Time
```
I actually expected a `DateTime` object as the type name implied?

**Comment by Azdaroth** [comment]
Hi @sarah-i-nbr, this is most likely related to ActiveModel itself and how the typecasting is handled for `datetime` type, looks a bit surprising, but maybe there is a reason why it is handled that way.

**Comment by sarah-i-nbr** [comment]
Thank you for the reply!
